/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: f04af5915822dda754648bb0c51ed6b8)
interface __BaseEnv_Env {
	CONNECTOR_PROVIDER: string;
	CONNECTOR_CONFIG_JSON: string;
	PUBLIC_ORIGIN: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	PROVIDER_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONNECTOR_PROVIDER" | "CONNECTOR_CONFIG_JSON" | "PUBLIC_ORIGIN" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "PROVIDER_TOKEN">> {}
}
